// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bartRcppMono
List bartRcppMono(IntegerVector yobs, NumericVector y_, NumericVector x_, NumericVector xpred_, IntegerVector yobs0, NumericVector y0_, NumericVector x0_, NumericVector xpred0_, int n00, List xinfo_list, int burn, int nd, int m, double kfac, double offset, double offset0);
RcppExport SEXP _monbart_bartRcppMono(SEXP yobsSEXP, SEXP y_SEXP, SEXP x_SEXP, SEXP xpred_SEXP, SEXP yobs0SEXP, SEXP y0_SEXP, SEXP x0_SEXP, SEXP xpred0_SEXP, SEXP n00SEXP, SEXP xinfo_listSEXP, SEXP burnSEXP, SEXP ndSEXP, SEXP mSEXP, SEXP kfacSEXP, SEXP offsetSEXP, SEXP offset0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type yobs(yobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpred_(xpred_SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type yobs0(yobs0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y0_(y0_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x0_(x0_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xpred0_(xpred0_SEXP);
    Rcpp::traits::input_parameter< int >::type n00(n00SEXP);
    Rcpp::traits::input_parameter< List >::type xinfo_list(xinfo_listSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type kfac(kfacSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type offset0(offset0SEXP);
    rcpp_result_gen = Rcpp::wrap(bartRcppMono(yobs, y_, x_, xpred_, yobs0, y0_, x0_, xpred0_, n00, xinfo_list, burn, nd, m, kfac, offset, offset0));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_treesample_module();

static const R_CallMethodDef CallEntries[] = {
    {"_monbart_bartRcppMono", (DL_FUNC) &_monbart_bartRcppMono, 16},
    {"_rcpp_module_boot_treesample_module", (DL_FUNC) &_rcpp_module_boot_treesample_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_monbart(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
