# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bartRcppMono <- function(yobs, y_, x_, xpred_, yobs0, y0_, x0_, xpred0_, n00, xinfo_list, burn, nd, m, kfac, offset, offset0) {
    .Call('_monbart_bartRcppMono', PACKAGE = 'monbart', yobs, y_, x_, xpred_, yobs0, y0_, x0_, xpred0_, n00, xinfo_list, burn, nd, m, kfac, offset, offset0)
}

